import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
// import speed from "../"
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const speed = localFont({
  src: [
    // {
    //   path: "./../public/fonts/speed.ttf",
    //   weight: "700",
    //   style: "italic",
    // },
    {
      path: "../public/fonts/SpeedRegular.woff",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/SpeedRegular.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-speed",
  display: "swap",
});
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  //  weight:400,
  variable: "--font-space-grotesk",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "PTR Regional Coaches Conference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${speed.variable} ${spaceGrotesk.variable}`}>
      <body className={`${speed.variable}`}>
        <div className={`${spaceGrotesk.className}`}>
          <Navbar />
        </div>
        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
